set verify off
set heading off
set long 9999

SELECT DBMS_METADATA.GET_DDL('USER',UPPER('&&user')) FROM dual;
SELECT DBMS_METADATA.GET_GRANTED_DDL('ROLE_GRANT',UPPER('&&user')) from dual;
SELECT DBMS_METADATA.GET_GRANTED_DDL('OBJECT_GRANT',UPPER('&&user')) from dual;
SELECT DBMS_METADATA.GET_GRANTED_DDL('SYSTEM_GRANT',UPPER('&&user')) from dual;
