-- how frequently are redo logs switching?
set pagesize 50

SELECT TO_CHAR(FIRST_TIME,'YYYY-MM-DD HH24')
  ||':00' HOUR,
  COUNT(*) "TOTAL LOG SWITCHES"
FROM GV$LOG_HISTORY
WHERE FIRST_TIME > SYSDATE - 2
GROUP BY TO_CHAR(FIRST_TIME,'YYYY-MM-DD HH24')
ORDER BY TO_CHAR(FIRST_TIME,'YYYY-MM-DD HH24') ASC;
