-- list stale table and index stats

set linesize 200
set pagesize 100

col owner format a15
col stale_stats format a15

SELECT OWNER, INDEX_NAME AS "NAME", OBJECT_TYPE, NUM_ROWS, SAMPLE_SIZE, LAST_ANALYZED, STALE_STATS
FROM DBA_IND_STATISTICS
WHERE OWNER NOT IN ('SYS','SYSTEM','XDB','DBSNMP') and STALE_STATS='YES'
UNION ALL
SELECT OWNER, TABLE_NAME AS "NAME", OBJECT_TYPE, NUM_ROWS, SAMPLE_SIZE, LAST_ANALYZED, STALE_STATS
FROM DBA_TAB_STATISTICS
WHERE OWNER NOT IN ('SYS','SYSTEM','XDB','DBSNMP') AND STALE_STATS='YES' 
ORDER BY OBJECT_TYPE, OWNER;
